// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfltlvkiglukppjqoxwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmbHRsdmtpZ2x1a3BwanFveHduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMDYzNjAsImV4cCI6MjA2NjY4MjM2MH0.VTMaE1R-KuqKTzqQWnjIvaiWM5vK-Y7VTnYT9wXc7o8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});